### ISSUE TITLE
Dynamic initial value for ACSlider

### ISSUE THREAD

**Issue by RomanPodymov** [RedMadRobot/ACSlider#1]
Hello @firmach,
Thank you for the library, it's very interesting.
I just want to ask you why `ACSlider.value`'s setter is defined as `private`? What if someone wants to show the slider in the middle of the screen before user interaction?

**Comment by firmach** [comment]
Hi!
Yeah, that's great suggestion!

I see two cases for public `value` setter:
— to set initial value, as you mention
— to update value while reacting to some other actions

Because of the second case I decided to move this feature out of the "MVP" scope. It wasn't necessary for our [Alarm-Clock](https://github.com/RedMadRobot/Alarm-Clock) project.

But it is really nice to have feature.
